version: "3.9"

services:
  app:
    container_name: toolbox-frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    command: npm start
